# Azure Container Registry Configuration
resource_group: "RG-ITSS-DEVOPS-ACR-PRD-AUE"
location: "Australia East"

# Common tags for all ACRs
tags:
  CostCenter: "CC-428900"
  BusinessUnit: "PlatformEngineering"
  Application: "DevOpsTooling"
  Environment: "PROD"
  Owner: "platform-engineering@rba.com"
  DataClassification: "Internal"
  ManagedBy: "terraform"
  TerraformModule: "acr"
  ModuleVersion: "v1.0.0"

# Container Registry definitions
container_registries:
  - name: "critssdevopsprdaue01"
    private_endpoint:
      name: "pep-itss-devops-acr-aue-01"
      subnet:
        name: "snet-privatelink"
        resource_group: "rg-acr-bundle-demo"
        vnet_name: "vnet-spoke1"
  
  - name: "critssdevopsprdaue02"
    private_endpoint:
      name: "pep-itss-devops-acr-aue-02"
      subnet:
        name: "snet-privatelink"
        resource_group: "rg-acr-bundle-demo"
        vnet_name: "vnet-spoke2"